# -*- coding: utf-8 -*-
"""HIES_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRLCB8UvlQeOi6YFENdMj1Z2F132pQlD

**Step 1: Import Libraries and Load Data**

The code starts by importing the necessary libraries: pandas for data manipulation and files for handling file uploads in Google Colab. Then, prompting the user to upload a CSV file using the files.upload() function from Google Colab. Once the file is uploaded, its name is retrieved and stored in the variable file_name for further processing. This step ensures user interaction, allowing flexibility to work with any CSV dataset. The uploaded file is loaded into a pandas DataFrame with pd.read_csv(file_name), which is used to store and manipulate the data easily.
"""

import pandas as pd
from google.colab import files

# Upload the CSV file
print("Please upload your CSV file:")
uploaded = files.upload()

# Get the uploaded file name
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

"""**Step 2: Data Cleaning**

a) Removing Duplicate Rows
*   Duplicate rows in the DataFrame are removed using the drop_duplicates() method to ensure data consistency and avoid redundancy during further analysis.

b) Handling Missing Values
*   Numeric Columns: Missing values in numeric columns are filled with the column's mean, ensuring no loss of data while maintaining realistic values.
Categorical Columns: Missing values in categorical columns are replaced with the string "Unknown," preserving data continuity while clearly marking missing entries.

This systematic handling of missing values enhances the dataset's quality and reliability for analysis.


"""

# Remove duplicate rows
df = df.drop_duplicates()

# Handle missing values
# Fill missing numeric values with the column mean
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Fill missing categorical values with "Unknown"
categorical_cols = df.select_dtypes(include=['object']).columns
df[categorical_cols] = df[categorical_cols].fillna("Unknown")

"""**Step 3: Combine "Wilayah Persekutuan" Rows**

For states listed under "Wilayah Persekutuan" (Kuala Lumpur, Labuan, and Putrajaya), their names are standardized to "Wilayah Persekutuan" in the state column, provided this column exists. This is achieved using the replace() method. The script also prints the unique values in the state column for debugging purposes to verify the changes.

Next, the data is grouped by date and state, and the numeric columns are aggregated using their mean values. This ensures that values for the combined rows are represented meaningfully without duplication.
"""

# Combine "Wilayah Persekutuan" Rows
wilayah_rows = ["W.P. Kuala Lumpur", "W.P. Labuan", "W.P. Putrajaya"]
combined_row_label = "Wilayah Persekutuan"

# Replace state names for Wilayah Persekutuan
if 'state' in df.columns:
    df['state'] = df['state'].replace(wilayah_rows, combined_row_label)

    # Debug: Check unique values in the state column
    print("\nUnique Values in 'state' Column After Replacement:")
    print(df['state'].unique())

# Group by 'date' and 'state', averaging numeric columns
def calculate_average_values(group):
    group = group.mean()  # Take the mean for numeric columns
    return group

# Apply groupby and aggregation
df_combined = (
    df.groupby(['date', 'state'], as_index=False)
    .apply(calculate_average_values)
    .reset_index(drop=True)
)

"""**Step 4: Save the Cleaned and Combined DataFrame**

The cleaned and processed DataFrame is saved as a CSV file (hies_state_cleaned_combined.csv). The to_csv() method is used to store the final output, with the index=False parameter ensuring the index is not written to the file.
"""

# Save the cleaned and combined DataFrame
output_file = "hies_state_cleaned_combined.csv"
df_combined.to_csv(output_file, index=False)

"""**Step 5: Download the Updated File**

Finally, the updated file is made available for download using the files.download() function, making it convenient for the user to access the processed dataset. The modified DataFrame is also displayed using the head() method, providing a preview of the first few rows to confirm successful processing.
"""

# Download the updated file
print("\nFile processed. Click the link below to download:")
files.download(output_file)

# Debug: Display the final modified DataFrame
print("\nModified DataFrame:")
print(df_combined.head())